model_name: "Qwen/Qwen3-4B-Instruct-2507"

dataset_path: "data/train.jsonl"
eval_dataset_path: "data/val.jsonl"

output_dir: "outputs/nemo_gym"
run_name_prefix: "nemo_gym"
report_to: "wandb"
project_name: "trl-nemo-gym"
log_completions: true
num_completions_to_print: 2

learning_rate: 1.0e-5
max_steps: 1000
num_generations: 8
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
max_seq_length: 16384
warmup_steps: 10
lr_scheduler_type: "linear"
optim: "adamw_torch_fused"
weight_decay: 0.0
vllm_importance_sampling_correction: false

temperature: 1.0
top_p: 0.999

save_steps: 100

eval_strategy: "steps"
eval_steps: 50

