model_name: "Qwen/Qwen3-4B-Instruct-2507"
dataset_path: "train-workplace.jsonl"

task: "workplace-assistant"  # used in wandb run_name if not set explicitly

output_dir: "outputs/trl_nemo_gym_workplace"
project_name: "cmunley-nemo-gym-trl-int"

learning_rate: 1.0e-5
max_steps: 1000000

num_generations: 16
per_device_train_batch_size: 1
gradient_accumulation_steps: 128

max_seq_length: 16384

temperature: 1.0
top_p: 0.999
weight_decay: 0.01
warmup_ratio: 0.0
lr_scheduler_type: "linear"
optim: "adamw_8bit"

save_steps: 900000
report_to: "wandb"